config/routes.rb
Rails.application.routes.draw do
  
  root "welcome#index"  

  resources :team_names
  resources :students
  
  get 'welcome/about' => 'welcome#about'
  get 'about' => 'welcome#about'

  get 'welcome/index' => 'welcome#index'
  get 'index' => 'welcome#index'

  get 'welcome/teamlists'
  get 'teamlists' => 'welcome#teamlists'
  post 'welcome/teamlists' => 'welcome#teamlists'
  

end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/team_name.rb
class TeamName < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name)
    end
end

app/controllers/team_names_controller.rb
class TeamNamesController < ApplicationController
  before_action :set_team_name, only: [:show, :edit, :update, :destroy]

  # GET /team_names
  # GET /team_names.json
  def index
    @team_names = TeamName.all
  end

  # GET /team_names/1
  # GET /team_names/1.json
  def show
  end

  # GET /team_names/new
  def new
    @team_name = TeamName.new
  end

  # GET /team_names/1/edit
  def edit
  end

  # POST /team_names
  # POST /team_names.json
  def create
    @team_name = TeamName.new(team_name_params)

    respond_to do |format|
      if @team_name.save
        format.html { redirect_to @team_name, notice: 'Team name was successfully created.' }
        format.json { render :show, status: :created, location: @team_name }
      else
        format.html { render :new }
        format.json { render json: @team_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_names/1
  # PATCH/PUT /team_names/1.json
  def update
    respond_to do |format|
      if @team_name.update(team_name_params)
        format.html { redirect_to @team_name, notice: 'Team name was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_name }
      else
        format.html { render :edit }
        format.json { render json: @team_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_names/1
  # DELETE /team_names/1.json
  def destroy
    @team_name.destroy
    respond_to do |format|
      format.html { redirect_to team_names_url, notice: 'Team name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_name
      @team_name = TeamName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_name_params
      params.require(:team_name).permit(:teams)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
include WelcomeHelper

  def index
  end
  
  def about
  end

  def teamlists
    
   	name = params[:name]
   	teams = params[:teams]
  	@students = Student.all
  	@teamxs = TeamName.all

    @players = []
    list_maker @students, @players

    @teamnames = []
    team_maker @teamxs, @teamnames

    roster_maker @players, @teamnames
 
  end 
end 


 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/team_names_helper.rb
module TeamNamesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  
  def list_maker x, y
    x.each do |student|
      y.push(student.name)
    end 
  end

  def team_maker x, y
    x.each do |student|
      y.push(student.teams)
    end 
  end  

  def roster_maker (players, teamnames)
    rand_players = []
    rand_players = @players.shuffle

    stop = @players.length/@teamnames.length
    add = (@players.length - (stop * @teamnames.length))

    teamlist = []
    (1..stop).each do
      @teamnames.each do |name|
        teamlist.push(name)
      end
    end

    i = 0
    while i < add
      teamlist.push(@teamnames[i])
      i = i + 1
    end

    sorted_list = []
    sorted_list = teamlist.sort

    @roster = {}
    rand_players.each_with_index {|k,i|@roster[k] = sorted_list[i]}
    return @roster
   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

	 <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

  <title>TeamMaker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

  <body style='width:1000px; margin: auto'>
    <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class="navbar-brand" href="/welcome/index">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <ul class="nav navbar-nav">
      <li><a href="/welcome/teamlists">Team Rosters</a></li>
      <li><a href="/students">Members</a></li>
      <li><a href="/team_names">Team Names</a></li>  
      <li><a href="/welcome/about">About Us</a></li>     
    </ul>
    </div>
  </div>

</nav>
<div class="container"
<%= yield %>
</div>
</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Team Maker</h1>

+<h2>Input Team Members</h2>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>




<u><%= link_to 'New Member', new_student_path %></u>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/team_names/_form.html.erb
<%= form_for(@team_name) do |f| %>
  <% if @team_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_name.errors.count, "error") %> prohibited this team_name from being saved:</h2>

      <ul>
      <% @team_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teams %><br>
    <%= f.text_field :teams %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_names/edit.html.erb
<h1>Editing team_name</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_name %> |
<%= link_to 'Back', team_names_path %>

app/views/team_names/index.html.erb
<h1>Input Team Names</h1>


<br><br>

<table>
  <thead>
    <tr>
      <th>Teams</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @team_names.each do |team_name| %>
      <tr>
        <td><%= team_name.teams %></td>
        <td><%= link_to 'Show', team_name %></td>
        <td><%= link_to 'Edit', edit_team_name_path(team_name) %></td>
        <td><%= link_to 'Destroy', team_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<u><%= link_to 'New Team Name', new_team_name_path %></u>

app/views/team_names/new.html.erb
<h1>New team_name</h1>

<%= render 'form' %>

<%= link_to 'Back', team_names_path %>

app/views/team_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teams:</strong>
  <%= @team_name.teams %>
</p>

<%= link_to 'Edit', edit_team_name_path(@team_name) %> |
<%= link_to 'Back', team_names_path %>

app/views/welcome/about.html.erb
<p><h1>About Us</h1></p>

<p><h4>We are students at Tech Talent South taking the Summer 2014 Ruby on Rails course as taught by TJ Muehlman.  This is our first team project utilizing GitHub as a way to share and coordinate code for building our joint project.  </h4>
</p>
<br><br>
<p><table>

  <tr>
    <td><%=image_tag("kimandmegan.jpg", class:"img-rounded img-border", height: '200', width: '260')%></td>
    <td><h5>Kim: needs to be committed .....seriously!!</h5></td>
  </tr>

  <tr>
    <td><%=image_tag("mike_phone.JPG", class:"img-rounded img-border", height: '200',width: '260')%></td>
    <td><h5>I am a student at TTS and this is our website.</h5></td>
  </tr>

  <tr>
    <td><%=image_tag("SamSkinner.JPG", class:"img-rounded img-border", height: '200',width: '260')%></td>

    <td><h5>Sam Skinner: biologist, entrepreneur, is seeking a new career as a web developer, specializing in Ruby on Rails.  He is a single father having raised two daughters from birth.  He enjoys hiking, kayaking and camping as well as a very wide variety of music.  

    He also is an advocate for creating a new domain name: ".duh" as a place for comedy!</h5></td>
  </tr>
</table></p>

app/views/welcome/index.html.erb
<h1>Welcome to ...</h1>

<h2>Team Maker</h2>
<br>
<p>If you need teams made randomly, this is the place!<p><br>
<p>All you need to do is input the team members' names. then the names you want for the teams.<p><br> 
<p>After you've entered them, return here to create team rosters.</p>
<br>
<br>


  <br>
<div>
  <%=form_tag ('/welcome/teamlists') do %>
    <%=submit_tag 'Show Teams!'%>
  <%end%>
</div>

app/views/welcome/teamlists.html.erb
<h1>Team Rosters</h1>
<br>
<br>
<div>
  <u><%=link_to "Go Again", root_path%></u>   


</div>
<br>
<br>
x
<table>
  <thead>
    <tr>
      <th>Teams</th>
      <th>Players</th>
    </tr>
  </thead>
  <tbody>
    <tr>  	
      <td><%@roster.each do | name, team |%>
	     <%="#{team}: #{name}"%><br>
      <%end%></td>
    </tr>
  </tbody>
</table>